services:
  frontend:
    container_name: qwikapp
    build:
      context: ./QwikApp
      dockerfile: ./Dockerfile
    #ports:
    #  - "3001:3000"
  backend:
    container_name: nodebackend
    build:
      context: ./NodeBackend
      dockerfile: ./Dockerfile
    #ports:
    #  - "3000:3000"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./pgdata:/var/lib/postgres/data
    #ports:
    #  - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - backend
      - frontend
